# apiVersion: backstage.io/v1alpha1
# kind: User
# metadata:
#   name: itayara
# spec:
#   profile:
#     displayName: Ibrahim Tayara
#     email: ibrtayyara@hotmail.com
#     picture: https://example.com/staff/jenny-with-party-hat.jpeg
#   memberOf: [central-it]
# ---
# apiVersion: backstage.io/v1alpha1
# kind: Group
# metadata:
#   name: central-it
#   description: The infra business unit
# spec:
#   type: business-unit
#   profile:
#     displayName: Central IT
#     email: it@example.com
#     picture: https://example.com/groups/bu-infrastructure.jpeg
#   parent: ops
#   children: [backstage, other]
#   members: [itayara]
# ---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: bobittay1221-terraform-azure-infra
  description: Stack bobittay1221
spec:
  owner: cnetral-it
# ---
# apiVersion: backstage.io/v1alpha1
# kind: Component
# metadata:
#   name: bobittay1221-azure-vnet
#   annotations:
#     github.com/project-slug: ibrt2016/terraform-azure-web-bobittay1221 # Change the value to your github repo which contains terraform code.
#     backstage.io/techdocs-ref: dir:.
#   links:
#   - url: https://github.com/claranet/terraform-azurerm-vnet
#     title: 'Virtual Network Terraform Module'
#     icon: github
#   tags:
#     - azure
#     - vnet
#     - terraform
#     - high-criticality
#     - ticket-number-23522
#     - entity-us
#     - owner-bob-tayara
#     - stack-bobittay1221
#     - created-on-2024-07-31
#   title: 'Stack bobittay1221 - Azure Virtal Network ' # you can give any title
#   description: |
#    **Azure Virtual Network** in stack **bobittay1221**\
#    \
#    **Ticket number:**  23522\
#    **Created on:**     2024-07-31\
#    **Azure region:**   us-east\
#    **Stack name:**     bobittay1221\
#    **Stack owner:**    bob-tayara\
#    **Azure subscription:**  web\
#    **Criticality:**  High\
#    **Entity:**  US\
#    **Cost center:**  00000
# spec:
#   type: azure-resource
#   owner: central-it
#   system: bobittay1221-terraform-azure-infra
#   lifecycle: production